贡献者行为准则
= Contributor Code of Conduct

作为这个项目的贡献者和维护者，为了培养一个开放而受欢迎的社区，我们承诺尊重所有通过报告问题、
发布功能请求、更新文档、提交拉请求或补丁以及其他活动做出贡献的人。
As contributors and maintainers of this project, and in the interest of fostering an open
and welcoming community, we pledge to respect all people who contribute through reporting
issues, posting feature requests, updating documentation, submitting pull requests or
patches, and other activities.


我们致力于使每个人都能在参与这个项目时免受骚扰，无论其经验水平、性别、性别认同和表达、性取向、残疾、
个人外貌、体型、种族、民族、年龄、宗教或国籍。
We are committed to making participation in this project a harassment-free experience for
everyone, regardless of level of experience, gender, gender identity and expression,
sexual orientation, disability, personal appearance, body size, race, ethnicity, age,
religion, or nationality.

参与者不可接受的行为包括:
Examples of unacceptable behavior by participants include:

性化的语言或意象的使用
人身攻击
挑衅或侮辱/贬损的评论
公众或私人骚扰
公布他人的私人信息，如物理地址或电子地址，没有明确的许可
其他不道德或不专业的行为
* The use of sexualized language or imagery
* Personal attacks
* Trolling or insulting/derogatory comments
* Public or private harassment
* Publishing other's private information, such as physical or electronic addresses,
  without explicit permission
* Other unethical or unprofessional conduct

项目维护者有权也有责任删除、编辑或拒绝注释、提交、代码、wiki编辑、问题和其他与此不一致的内容
行为准则，或暂时或永久禁止任何贡献者的其他行为，他们认为不适当的，威胁，攻击性，或有害的。
Project maintainers have the right and responsibility to remove, edit, or reject comments,
commits, code, wiki edits, issues, and other contributions that are not aligned to this
Code of Conduct, or to ban temporarily or permanently any contributor for other behaviors
that they deem inappropriate, threatening, offensive, or harmful.

通过采用这一行为准则，项目维护者承诺他们将公平和一致地将这些原则应用到项目管理的各个方面。
不遵守或执行行为准则的项目维护者可能会被永久地从项目团队中删除。
By adopting this Code of Conduct, project maintainers commit themselves to fairly and
consistently applying these principles to every aspect of managing this project. Project
maintainers who do not follow or enforce the Code of Conduct may be permanently removed
from the project team.

当个人代表项目或其社区时，本行为守则适用于项目空间和公共空间。
This Code of Conduct applies both within project spaces and in public spaces when an
individual is representing the project or its community.

滥用、骚扰或其他不可接受的行为的实例可以通过联系spring-code-of-conduct@pivotal.io项目维护人员来报告。
所有投诉均会得到检讨和调查，并会根据情况作出必要和适当的回应。维护人员有义务对事件的报告者保密。
Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by
contacting a project maintainer at spring-code-of-conduct@pivotal.io . All complaints will
be reviewed and investigated and will result in a response that is deemed necessary and
appropriate to the circumstances. Maintainers are obligated to maintain confidentiality
with regard to the reporter of an incident.

本行为准则改编自
This Code of Conduct is adapted from the
https://contributor-covenant.org[Contributor Covenant], version 1.3.0, available at
https://contributor-covenant.org/version/1/3/0/[contributor-covenant.org/version/1/3/0/]
